replace tab with 4sp

diff --git a/pcc b/pcc
--- a/pcc
+++ b/pcc
@@ -6,8 +6,8 @@ PCC=$DIR/../cproc/cproc-qbe
 usage()
 {
   echo $flags
-	echo "usage: mcc [cc flags] file.c" >&2
-	exit 1
+  echo "usage: mcc [cc flags] file.c" >&2
+  exit 1
 }
 
 for i
@@ -18,7 +18,7 @@ done
 
 if test -z $file
 then
-	usage
+  usage
 fi
 
 file2="${file%.*}"
@@ -27,6 +27,6 @@ $PCC < $file2.p > $file2.q
 
 if test $? -ne 0
 then
-#	echo "error processing file $file" >&2
-	exit 1
+# echo "error processing file $file" >&2
+  exit 1
 fi
diff --git a/qq b/qq
--- a/qq
+++ b/qq
@@ -5,29 +5,29 @@ QBE=$DIR/../qbe/qbe
 
 usage()
 {
-	echo "usage: qq file.q" >&2
-	exit 1
+  echo "usage: qq file.q" >&2
+  exit 1
 }
 
 for i
 do
-	case $i in
-	-*)
-		flags="$flags $i"
-		;;
-	*)
-		if ! test -z $file
-		then
-			usage
-		fi
-		file=$i
-		;;
-	esac
+  case $i in
+  -*)
+    flags="$flags $i"
+    ;;
+  *)
+    if ! test -z $file
+    then
+      usage
+    fi
+    file=$i
+    ;;
+  esac
 done
 
 if test -z $file
 then
-	usage
+  usage
 fi
 
 file2="${file%.*}"
@@ -38,7 +38,7 @@ cc -o $file2 $file2.o -L$DIR/lib -lbuckets -lpp -lc
 
 if test $? -ne 0
 then
-	echo "error processing file $file" >&2
-	exit 1
+  echo "error processing file $file" >&2
+  exit 1
 fi
 
